# Generated by Django 4.1.5 on 2023-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_tasks_author_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(related_name='label', through='tasks.TaskTolabels', to='labels.labels'),
        ),
    ]
