# Generated by Django 4.1.5 on 2023-03-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_executor'),
        ('tasks', '0005_alter_tasks_labels'),
    ]

    operations = [
    ]
