# Generated by Django 4.1.5 on 2023-03-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0007_alter_tasks_executor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTolabels',
            new_name='TasksToLabels',
        ),
    ]
