# Generated by Django 4.1.5 on 2023-03-12 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0003_alter_statuses_name'),
        ('tasks', '0009_alter_tasks_author_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='label', through='tasks.TasksToLabels', to='labels.labels', verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.statuses', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
