# Generated by Django 4.1.5 on 2023-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasks_executor_alter_tasks_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
